### ISSUE TITLE
Kütüphanenin lisansı (MIT,BSD,GPL, vs.)  hakkında bilgi yok.

### ISSUE THREAD

**Issue by myexamples1423** [ArduinoHaber/kapadokya-gsm-shield-library#1]
Kütüphanenizin lisansı (MIT,BSD,GPL, vs.) hakkında hiçbir bilgi vermemişsiniz. Bu şekilde kütüphaneyi
hiç bir kimse kullanamaz çünkü kütüphanenin tüm hakları saklı olur. Lütfen kütüphanenize uygun bir lisans belirtiniz.

**Comment by ArduinoHaber** [comment]
Merhaba,

Öneriniz için teşekkür ederim, haklısınız. En kısa zamanda düzenleyeceğim.


https://YouTube.com/ArduinoHaberTV

Saygılarımla...

Emre KONCA
Arduino Haber
Sistem Mühendisi

**Comment by myexamples1423** [comment]
Bu arada kütüph

**Comment by myexamples1423** [comment]
Bu arada kütüphaneyi direk zip dosyası olarak Github'a yüklemenize gerek yok. Github'ta zip dosyası olarak indirme seçeneği var.
